name: .NET Build

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Test with dotnet
      working-directory: ./src
      run: dotnet test --configuration Release

    - name: Package NuGet
      working-directory: ./src
      run: dotnet pack --include-symbols --include-source --configuration Release

    - name: Upload Nuget Spice86.Aeon
      working-directory: ./src/Spice86.Aeon/bin/Release
      run: nuget push Spice86.Aeon.4.0.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Bufdio.Spice86
      working-directory: ./src/Bufdio.Spice86/bin/Release
      run: nuget push Bufdio.Spice86.4.0.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86.Shared
      working-directory: ./src/Spice86.Shared/bin/Release
      run: nuget push Spice86.Shared.4.0.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86.Logging
      working-directory: ./src/Spice86.Logging/bin/Release
      run: nuget push Spice86.Logging.4.0.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86.Core
      working-directory: ./src/Spice86.Core/bin/Release
      run: nuget push Spice86.Core.4.0.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

    - name: Upload NuGet Spice86
      working-directory: ./src/Spice86/bin/Release
      run: nuget push Spice86.4.0.2.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate
